In [ ]:
# exercise_1: Array Creation and Manipulation
# تمرین_1: ایجاد و دستکاری آرایه
import numpy as np

print("1. Array Creation and Manipulation")
# Create a 3x3 array of random numbers between 1 and 100
#یک آرایه 3×3 از اعداد تصادفی بین 1 تا 100 ایجاد کنید
arr = np.random.randint(1, 101, size=(3, 3))
print("3x3 random array:")
print(arr)

# Find the minimum and maximum values
# حداقل و حداکثر مقادیر را پیدا کنید
print("Minimum amount:", np.min(arr))
print("Maximum value:", np.max(arr))

# Calculate the sum of each row
# مجموع هر ردیف را محاسبه کنید
print("Total of each row:")
print(np.sum(arr, axis=1))

# Calculate the product of each column
# حاصل ضرب هر ستون را محاسبه کنید
print("The product of each column:")
print(np.prod(arr, axis=0))

# Normalize the array
# آرایه را عادی کنید
arr_normalized = (arr - np.mean(arr)) / np.std(arr)
print("Normalized array:")
print(arr_normalized)

1. Array Creation and Manipulation
آرایه تصادفی 3x3:
[[17 39 75]
 [ 6  7 80]
 [30 46 65]]
حداقل مقدار: 6
حداکثر مقدار: 80
مجموع هر ردیف:
[131  93 141]
حاصلضرب هر ستون:
[  3060  12558 390000]
آرایه نرمال شده:
[[-0.88623063 -0.05852466  1.29590328]
 [-1.30008361 -1.26246061  1.48401827]
 [-0.39713165  0.20483632  0.91967329]]


In [12]:
# exercise_2 : Array Reshaping and Broadcasting
# تمرین_2: تغییر شکل آرایه و پخش
print("\n2. Array Reshaping and Broadcasting")
# Create a 1D array of numbers 1 to 12
# یک آرایه 1 بعدی از اعداد 1 تا 12 ایجاد کنید
arr1d = np.arange(1, 13)
print("1D array from 1 to 12:")
print(arr1d)

# Reshape to 4x3 array
# به آرایه 4x3 تغییر شکل دهید
arr3x4 = arr1d.reshape(3, 4)
print("3x4 array:")
print(arr3x4)

# Reshape to 4x3 array
# به آرایه 4x3 تغییر شکل دهید
arr4x3 = arr1d.reshape(4, 3)
print("4x3 array:")
print(arr4x3)

# Create a 3x1 array of ones and use spread to multiply with the 3x4 array
# یک آرایه 3x1 از یک ها ایجاد کنید و از spread برای ضرب در آرایه 3x4 استفاده کنید
arr3x1 = np.ones((3, 1))
arr3x4_broadcast = arr3x4 * arr3x1
print("3x4 array multiplied by 3x1 array:")
print(arr3x4_broadcast)

# Create a 1x4 array of doubles and use spread to add to the 3x4 array
#یک آرایه 1x4 از دوتایی ایجاد کنید و از spread برای اضافه کردن به آرایه 3x4 استفاده کنید
arr1x4 = np.full((1, 4), 2)
arr3x4_broadcast2 = arr3x4 + arr1x4
print("3x4 array with the addition of a 1x4 array:")
print(arr3x4_broadcast2)



2. Array Reshaping and Broadcasting
1D array from 1 to 12:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
3x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4x3 array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3x4 array multiplied by 3x1 array:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
3x4 array with the addition of a 1x4 array:
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [7]:
# exercise_3 : Indexing and Slicing
# تمرین_3 : نمایه سازی و برش
print("\n3. Indexing and Slicing")
# Create a 5x5 array of numbers 1 to 25
#یک آرایه 5×5 از اعداد 1 تا 25 ایجاد کنید
arr5x5 = np.arange(1, 26).reshape(5, 5)
print("آرایه 5x5 از 1 تا 25:")
print(arr5x5)

# Extract the central 3x3 subarray
# زیرآرایه مرکزی 3x3 را استخراج کنید
center_3x3 = arr5x5[1:4, 1:4]
print("زیرآرایه 3x3 مرکزی:")
print(center_3x3)

# Extract all elements in the second row
# تمام عناصر در ردیف دوم را استخراج کنید
row2 = arr5x5[1, :]
print("عناصر ردیف دوم:")
print(row2)

# Extract columns with odd index
# استخراج ستون ها با شاخص فرد
odd_cols = arr5x5[:, ::2]
print("ستون های با نمایه فرد:")
print(odd_cols)

# Extract elements larger than average with logical indexing
# عناصر بزرگتر از حد متوسط ​​را با نمایه سازی منطقی استخراج کنید
mean = np.mean(arr5x5)
greater_than_mean = arr5x5[arr5x5 > mean]
print("Elements larger than average:")
print(greater_than_mean)


3. Indexing and Slicing
آرایه 5x5 از 1 تا 25:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
زیرآرایه 3x3 مرکزی:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
عناصر ردیف دوم:
[ 6  7  8  9 10]
ستون های با نمایه فرد:
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]
عناصر بزرگتر از میانگین:
[14 15 16 17 18 19 20 21 22 23 24 25]


In [11]:
# exercise_4: Linear Algebra Operations
# تمرین_4: عملیات جبر خطی
print("\n4. Linear Algebra Operations")
# Create matrices A (2x3) and B (3x2)
# ایجاد ماتریس A (2x3) و B (3x2)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# Calculate the matrix product A.B
# محاسبه حاصل ضرب ماتریس A.B
AB = np.matmul(A, B)
print("Calculate the matrix product A.B :")
print(AB)

# Calculate the matrix product B.A
# محاسبه حاصل ضرب ماتریس B.A
BA = np.matmul(B, A)
print("Calculate the matrix product B.A :")
print(BA)

# Find the eigenvalues ​​and eigenvectors of A.B
# مقادیر ویژه و بردارهای ویژه A.B را پیدا کنید
eigenvalues, eigenvectors = np.linalg.eig(np.matmul(A, B))
print("Eigenvalues ​​and eigenvectors of A.B :")
print("eigenvalues :", eigenvalues)
print("eigenvectors :", eigenvectors)

# determinant B.A
det_BA = np.linalg.det(np.matmul(B, A))
print("determinant B.A:", det_BA)


4. Linear Algebra Operations
Calculate the matrix product A.B :
[[ 58  64]
 [139 154]]
Calculate the matrix product B.A :
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]
Eigenvalues ​​and eigenvectors of A.B :
eigenvalues : [1.69947557e-01 2.11830052e+02]
eigenvectors : [[-0.74196653 -0.38412512]
 [ 0.67043693 -0.92328105]]
determinant B.A: -1.7053025658242662e-13


In [9]:
#################################### exersize just myself ####################################

# N = np.array([[3,2,2],[3,2,1]])
# M = np.array([[3,1],[2,3],[3,2]])

# # print(np.matmul(N,M))
# # print(np.divide(N,M))

# eigenvalues , eigenvectors = np.linalg.eig(np.matmul(M,N))
# print(eigenvectors)
# print(eigenvalues)
# deterniant = np.linalg.det(np.matmul(M,N))
# print(deterniant)

# d = np.arange(1,37).reshape(6,6)
# print(d)
# print(d[: , 1::2])
# print(d[1::2,:])

# print(np.sum(d , axis=1))

# print(np.min(d))
# print(np.max(d))
# print(np.mean(d))

# arr_normalized = (arr - np.mean(arr)) / np.std(arr)
# print(arr_normalized)

# n = d[d> np.mean(d)]

# print(n)
# p = d[1:5,1:5]
# print(p)


[[ 5.07891594e-01  5.54700196e-01  5.43775679e-01]
 [ 5.98694741e-01 -8.32050294e-01 -8.38730955e-01]
 [ 6.19363170e-01 -2.40628459e-14  2.89550758e-02]]
[ 2.99666295e+01 -2.93981425e-14  3.33704529e-02]
0.0
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]
 [26 28 30]
 [32 34 36]]
[[ 7  8  9 10 11 12]
 [19 20 21 22 23 24]
 [31 32 33 34 35 36]]
[ 21  57  93 129 165 201]
1
36
18.5
[[-0.88623063 -0.05852466  1.29590328]
 [-1.30008361 -1.26246061  1.48401827]
 [-0.39713165  0.20483632  0.91967329]]
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
